# SPDX-License-Identifier: MIT
cc_binary(
    name = "worker",
    srcs = ["worker.cc", "//tests:price_table_builder_test_access.hpp"],
    deps = [
        "//src/option/table/parquet:parquet_io",
        "//src/option/table/bspline:bspline_builder",
        "//src/option/table:analytical_eep",
        "//src/math/bspline:bspline_nd",
        "//src/math/bspline:bspline_basis",
    ],
    copts = ["-fopenmp"],
    linkopts = ["-fopenmp"],
    tags = ["manual"],
)
