# SPDX-License-Identifier: MIT
cc_binary(
    name = "continuous_bspline",
    srcs = ["continuous_bspline.cc"],
    deps = [
        "//src/option:price_table_factory",
        "//src/option:american_option",
        "//src/option:grid_spec_types",
        "//src/option/table/bspline:bspline_surface",
        "//src/option/table/serialization:from_data",
        "//src/option/table/certification:continuous_cell",
    ],
    copts = ["-O3", "-fopenmp"],
    linkopts = ["-fopenmp"],
    tags = ["manual"],
)
cc_binary(
    name = "constant_shift",
    srcs = ["constant_shift.cc"],
    deps = [
        "//src/option:price_table_factory",
        "//src/option/table/parquet:parquet_io",
        "//src/option/table/bspline:bspline_surface",
        "//src/option/table/serialization:from_data",
        "//src/option/table/certification:continuous_cell",
    ],
    copts = ["-O3", "-fopenmp"],
    linkopts = ["-fopenmp"],
    tags = ["manual"],
)
