# SPDX-License-Identifier: MIT

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "reference_qualification",
    srcs = ["reference_qualification.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "reference_consumption",
    srcs = ["reference_consumption.py"],
    deps = [":reference_qualification"],
    visibility = ["//visibility:public"],
)
